### ISSUE TITLE
Start talk at 00 min 00 sec

### ISSUE THREAD

**Issue by Leva16** [pikkewyn/talking-clock#1]
Hi, i read article in [omgubuntu](http://www.omgubuntu.co.uk/2016/09/linux-talking-clock-simple-script) and i like your work.
Bu i wonder, is it possible to do, that script start play time exactly at 00 min 00 sec every hour? 
Because it start speak between 40-50 sec. 
i`m not a perfectionist, but it would be nice. =) 

i tried add `sec=$(date +%S)` and `if [[ $minute -eq 00 ] && [$sec -eq 00]]`, 
but it didn't help, i'm not good in bash. Can you give me a hint?
Thank you.

**Comment by ildarkhasanshin** [comment]
./talking-clock -f
exactly 00 minutes and 00 seconds

ubuntu 16.04
only i have sound-files in home-dir
and edit config for program and main_dir

**Comment by Leva16** [comment]
`./talking-clock -f` run whit error:

> ./talking-clock: line 102: !=: command not found
> starting talking-clock 

and talking time between 40-50 sec

**Comment by ildarkhasanshin** [comment]
strangely
i displayed the same
but it triggered at exactly 00

**Comment by pikkewyn** [comment]
Hi @Leva16, thanks a lot for interest. I'm at work now but I can see couple of issues, which I will fix this weekend:
- incomplete README
- problem with passing empty flag
- need of some delay to start at 00 sec

**Comment by pikkewyn** [comment]
Hi!
@Leva16, reason for delay was moment when script is started. Most probably it never will be exactly 00 second as starting external player adds some minimal delay. But I've added kind of stabilizer so now it will start at most 00 + couple of seconds and that should be fine

**Comment by pikkewyn** [comment]
@Leva16 I've added delay correction into main loop and start time is not fluctuating anymore ( at least during 10 hours of testing )

**Comment by Leva16** [comment]
@pikkewyn  Thank you. Work like a charm, start at 00 min 00-01 sec.
